// mockData.js
// ---------------------------------------------------------------------------
// Fable's entire "backend" for this build: a static catalog, category list,
// and a couple of demo accounts. In a real system this would come from a
// product service / auth service — here it's a plain module so the app is
// fully functional offline, with zero network calls.
// ---------------------------------------------------------------------------

export const CATEGORIES = [
  { id: "books", label: "Books", icon: "book" },
  { id: "electronics", label: "Electronics", icon: "bolt" },
  { id: "home", label: "Home & Kitchen", icon: "home" },
  { id: "fashion", label: "Fashion", icon: "shirt" },
  { id: "office", label: "Office & School", icon: "pencil" },
  { id: "outdoors", label: "Outdoors", icon: "tent" },
  { id: "toys", label: "Toys & Games", icon: "dice" },
  { id: "beauty", label: "Beauty & Care", icon: "drop" },
];

// Small helper so every product gets a stable, deterministic "reviewers"
// count and a placeholder image without repeating ourselves 40+ times below.
const img = (seed, w = 600, h = 600) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const PRODUCTS = [
  // ---------------------------------------------------------------- BOOKS
  {
    id: "bk-001",
    category: "books",
    title: "The Lantern & the Loom",
    brand: "Harrow Press",
    price: 18.99,
    listPrice: 24.0,
    rating: 4.6,
    reviewCount: 2318,
    stock: 42,
    badge: "Bestseller",
    image: img("lantern-loom"),
    gallery: [img("lantern-loom"), img("lantern-loom-2"), img("lantern-loom-3")],
    description:
      "A generation-spanning novel about a family of weavers whose tapestries seem to predict the future — until one thread refuses to be woven.",
    bullets: [
      "New York Times bestseller, 2025",
      "Paperback, 412 pages",
      "Reading age: 14 and up",
      "Book club discussion guide included",
    ],
    reviews: [
      { author: "M. Okafor", rating: 5, title: "Could not put it down", body: "Finished this in two sittings. The pacing in the last third is relentless." },
      { author: "J. Park", rating: 4, title: "Slow start, huge payoff", body: "First 80 pages took some patience but it completely earns the ending." },
    ],
  },
  {
    id: "bk-002",
    category: "books",
    title: "Ordinary Constellations",
    brand: "Salt & Sage Books",
    price: 14.5,
    listPrice: 17.99,
    rating: 4.3,
    reviewCount: 891,
    stock: 67,
    image: img("constellations"),
    gallery: [img("constellations"), img("constellations-2")],
    description:
      "A quiet, observational short story collection about small towns, night shifts, and the astronomy of everyday attention.",
    bullets: ["Paperback, 256 pages", "12 interconnected short stories", "Includes author's note"],
    reviews: [
      { author: "R. Lindqvist", rating: 4, title: "Beautifully understated", body: "Not a lot happens plot-wise, but the prose does the heavy lifting." },
    ],
  },
  {
    id: "bk-003",
    category: "books",
    title: "The Cartographer's Apprentice",
    brand: "Harrow Press",
    price: 21.0,
    listPrice: 21.0,
    rating: 4.8,
    reviewCount: 5602,
    stock: 15,
    badge: "Limited stock",
    image: img("cartographer"),
    gallery: [img("cartographer"), img("cartographer-2"), img("cartographer-3")],
    description:
      "Fantasy debut about a mapmaker's apprentice who discovers that some places only exist because someone once drew them.",
    bullets: ["Hardcover, first edition", "544 pages", "Illustrated endpapers", "Book 1 of the Meridian Trilogy"],
    reviews: [
      { author: "T. Alvarez", rating: 5, title: "Best fantasy debut in years", body: "The magic system built around cartography is genuinely original." },
      { author: "S. Kim", rating: 5, title: "Gorgeous world-building", body: "I bought the physical copy just for the illustrated maps." },
    ],
  },
  {
    id: "bk-004",
    category: "books",
    title: "Kitchen Table Economics",
    brand: "Ledger House",
    price: 26.75,
    listPrice: 32.0,
    rating: 4.1,
    reviewCount: 344,
    stock: 88,
    image: img("kitchen-econ"),
    gallery: [img("kitchen-econ"), img("kitchen-econ-2")],
    description:
      "A plain-language guide to household finance, budgeting, and long-term saving, written by a former credit union analyst.",
    bullets: ["Paperback, 288 pages", "Includes worksheets", "No prior finance knowledge required"],
    reviews: [{ author: "D. Whitfield", rating: 4, title: "Practical, not preachy", body: "Refreshingly free of the usual finance-book platitudes." }],
  },
  {
    id: "bk-005",
    category: "books",
    title: "Field Notes on Silence",
    brand: "Salt & Sage Books",
    price: 12.25,
    listPrice: 15.0,
    rating: 4.4,
    reviewCount: 1203,
    stock: 51,
    image: img("field-notes"),
    gallery: [img("field-notes"), img("field-notes-2")],
    description:
      "Essays from a decade spent recording ambient sound in national parks — part nature writing, part meditation on attention.",
    bullets: ["Paperback, 198 pages", "16-page photo insert"],
    reviews: [{ author: "N. Brandt", rating: 5, title: "Perfect for slow mornings", body: "The essay on desert silence alone is worth the price." }],
  },
  {
    id: "bk-006",
    category: "books",
    title: "The Understudy's Guide to Vanishing",
    brand: "Harrow Press",
    price: 19.99,
    listPrice: 19.99,
    rating: 4.0,
    reviewCount: 276,
    stock: 5,
    badge: "Only 5 left",
    image: img("understudy"),
    gallery: [img("understudy"), img("understudy-2")],
    description:
      "A theater-world mystery: when the lead actress disappears mid-run, her understudy realizes she may be the only suspect who knows the script well enough to solve it.",
    bullets: ["Paperback, 336 pages", "Optioned for television"],
    reviews: [{ author: "L. Moreau", rating: 3, title: "Fun but predictable", body: "Guessed the twist by chapter 10, but enjoyed the ride anyway." }],
  },

  // --------------------------------------------------------- ELECTRONICS
  {
    id: "el-001",
    category: "electronics",
    title: "Aerowave 2 Wireless Headphones",
    brand: "Nordune",
    price: 89.99,
    listPrice: 129.99,
    rating: 4.5,
    reviewCount: 8734,
    stock: 120,
    badge: "Fable's Choice",
    image: img("aerowave-headphones"),
    gallery: [img("aerowave-headphones"), img("aerowave-2"), img("aerowave-3"), img("aerowave-4")],
    description:
      "Over-ear wireless headphones with active noise cancellation, 38-hour battery life, and a foldable frame for travel.",
    bullets: [
      "Active noise cancellation with transparency mode",
      "38 hours playback, 5-minute quick charge = 4 hours",
      "Bluetooth 5.3, multipoint pairing",
      "Memory-foam ear cushions",
    ],
    variants: { color: ["Slate Black", "Fog Grey", "Dune Sand"] },
    reviews: [
      { author: "K. Ibrahim", rating: 5, title: "ANC actually works", body: "Used these on a 14-hour flight, blocked out engine noise almost entirely." },
      { author: "A. Ferreira", rating: 4, title: "Great sound, so-so app", body: "Companion app is clunky but the headphones themselves are excellent." },
    ],
  },
  {
    id: "el-002",
    category: "electronics",
    title: "Kepler Mechanical Keyboard, Low-Profile",
    brand: "Norrbyte",
    price: 74.0,
    listPrice: 89.0,
    rating: 4.7,
    reviewCount: 3021,
    stock: 60,
    image: img("kepler-keyboard"),
    gallery: [img("kepler-keyboard"), img("kepler-2"), img("kepler-3")],
    description:
      "75% layout mechanical keyboard with hot-swappable switches, PBT keycaps, and per-key RGB.",
    bullets: ["Hot-swappable switch sockets", "PBT double-shot keycaps", "USB-C detachable cable", "Wireless + wired modes"],
    variants: { color: ["White", "Charcoal"], switch: ["Red (linear)", "Brown (tactile)"] },
    reviews: [{ author: "P. Sung", rating: 5, title: "Feels premium", body: "Keycaps and case have zero flex. Sound is thock-y in the best way." }],
  },
  {
    id: "el-003",
    category: "electronics",
    title: "Halcyon 27\" QHD Monitor",
    brand: "Nordune",
    price: 249.0,
    listPrice: 299.0,
    rating: 4.4,
    reviewCount: 1567,
    stock: 34,
    image: img("halcyon-monitor"),
    gallery: [img("halcyon-monitor"), img("halcyon-2")],
    description: "27-inch QHD IPS monitor, 165Hz refresh rate, 1ms response time, USB-C 90W power delivery.",
    bullets: ["2560×1440 IPS panel", "165Hz / 1ms GtG", "USB-C with 90W PD", "Height, tilt & swivel adjustable stand"],
    reviews: [{ author: "E. Nakamura", rating: 4, title: "Great for the price", body: "Color accuracy out of the box is surprisingly good for non-calibrated." }],
  },
  {
    id: "el-004",
    category: "electronics",
    title: "Compass Mini Portable SSD 1TB",
    brand: "Norrbyte",
    price: 64.99,
    listPrice: 84.99,
    rating: 4.6,
    reviewCount: 4410,
    stock: 200,
    badge: "Deal",
    image: img("compass-ssd"),
    gallery: [img("compass-ssd"), img("compass-ssd-2")],
    description: "Pocket-sized 1TB external SSD, USB-C 3.2 Gen 2, up to 1050MB/s read speeds, shock-resistant shell.",
    bullets: ["1TB capacity", "Up to 1050MB/s read", "IP55 dust/splash resistant", "Includes USB-C and USB-A cables"],
    reviews: [{ author: "V. Petrov", rating: 5, title: "Blazing fast", body: "Transferred a 40GB project folder in under a minute." }],
  },
  {
    id: "el-005",
    category: "electronics",
    title: "Driftlight Smart Desk Lamp",
    brand: "Home & Hearth",
    price: 39.99,
    listPrice: 49.99,
    rating: 4.2,
    reviewCount: 986,
    stock: 75,
    image: img("driftlight-lamp"),
    gallery: [img("driftlight-lamp"), img("driftlight-2")],
    description: "Adjustable LED desk lamp with 5 color temperatures, USB-C charging port, and touch dimming.",
    bullets: ["5 color temperatures, 10 brightness levels", "Built-in USB-C fast charge port", "Touch-sensitive controls", "Foldable, flat-pack design"],
    reviews: [{ author: "C. Dubois", rating: 4, title: "Solid desk companion", body: "The charging port is genuinely useful, didn't expect to use it this much." }],
  },
  {
    id: "el-006",
    category: "electronics",
    title: "Pathfinder GPS Sport Watch",
    brand: "Nordune",
    price: 159.0,
    listPrice: 199.0,
    rating: 4.3,
    reviewCount: 2245,
    stock: 40,
    image: img("pathfinder-watch"),
    gallery: [img("pathfinder-watch"), img("pathfinder-2")],
    description: "GPS multisport watch with 14-day battery, heart rate monitor, and offline route maps.",
    bullets: ["14-day battery life (GPS off)", "Built-in optical heart rate", "Offline topo maps", "5 ATM water resistance"],
    reviews: [{ author: "H. Solberg", rating: 4, title: "Battery life is real", body: "Genuinely lasted 12 days with daily GPS runs logged." }],
  },
  {
    id: "el-007",
    category: "electronics",
    title: "Aperture 4K Webcam",
    brand: "Norrbyte",
    price: 54.5,
    listPrice: 69.0,
    rating: 4.1,
    reviewCount: 674,
    stock: 90,
    image: img("aperture-webcam"),
    gallery: [img("aperture-webcam"), img("aperture-2")],
    description: "4K webcam with autofocus, dual noise-canceling mics, and a physical privacy shutter.",
    bullets: ["4K30 / 1080p60 recording", "Auto light correction", "Dual built-in microphones", "Physical privacy shutter"],
    reviews: [{ author: "F. Adeyemi", rating: 4, title: "Big upgrade from laptop cam", body: "Auto-exposure handles my backlit window well." }],
  },

  // -------------------------------------------------------- HOME & KITCHEN
  {
    id: "hk-001",
    category: "home",
    title: "Hearthstone 6-Qt Pressure Cooker",
    brand: "Home & Hearth",
    price: 79.99,
    listPrice: 99.99,
    rating: 4.7,
    reviewCount: 12045,
    stock: 55,
    badge: "Bestseller",
    image: img("hearthstone-cooker"),
    gallery: [img("hearthstone-cooker"), img("hearthstone-2"), img("hearthstone-3")],
    description:
      "6-quart multi-function pressure cooker: pressure cook, slow cook, sauté, steam, and warm — one pot, five appliances.",
    bullets: ["6-quart stainless steel inner pot", "10 built-in safety mechanisms", "Delayed start up to 24 hours", "Dishwasher-safe accessories"],
    reviews: [
      { author: "G. Alonso", rating: 5, title: "Replaced three appliances", body: "Sold my slow cooker and rice cooker after buying this. Use it weekly." },
      { author: "B. Novak", rating: 4, title: "Great, loud steam release", body: "Works exactly as described, just don't do the quick-release near a baby napping." },
    ],
  },
  {
    id: "hk-002",
    category: "home",
    title: "Coastline Ceramic Dutch Oven, 5.5L",
    brand: "Home & Hearth",
    price: 128.0,
    listPrice: 160.0,
    rating: 4.8,
    reviewCount: 3390,
    stock: 22,
    image: img("dutch-oven"),
    gallery: [img("dutch-oven"), img("dutch-oven-2")],
    description: "Enameled cast iron Dutch oven, 5.5 liter capacity, oven-safe to 500°F.",
    bullets: ["Enameled cast iron construction", "Oven safe to 500°F", "Fits standard stovetops and induction", "Lifetime warranty"],
    variants: { color: ["Cream", "Harbor Blue", "Clay Red"] },
    reviews: [{ author: "S. Marchetti", rating: 5, title: "Heirloom quality", body: "Heavier than I expected, in the best way. Braises come out perfect." }],
  },
  {
    id: "hk-003",
    category: "home",
    title: "Wickerbrook Woven Storage Baskets (Set of 3)",
    brand: "Fern & Field",
    price: 42.0,
    listPrice: 52.0,
    rating: 4.4,
    reviewCount: 1102,
    stock: 63,
    image: img("wicker-baskets"),
    gallery: [img("wicker-baskets"), img("wicker-2")],
    description: "Handwoven seagrass storage baskets in three nesting sizes, with cotton liner and carry handles.",
    bullets: ["Set of 3 nesting sizes", "Removable cotton liners", "Handwoven natural seagrass"],
    reviews: [{ author: "Y. Tanaka", rating: 4, title: "Great for linen closet", body: "Slight seagrass smell for the first week, faded after airing out." }],
  },
  {
    id: "hk-004",
    category: "home",
    title: "Mistfall Ultrasonic Cool Mist Humidifier",
    brand: "Home & Hearth",
    price: 45.99,
    listPrice: 59.99,
    rating: 4.3,
    reviewCount: 5588,
    stock: 84,
    image: img("mistfall-humidifier"),
    gallery: [img("mistfall-humidifier"), img("mistfall-2")],
    description: "4L ultrasonic humidifier with quiet operation, auto shut-off, and adjustable mist output.",
    bullets: ["4-liter tank, up to 40 hours runtime", "Whisper-quiet ultrasonic operation", "Auto shut-off when empty", "Optional night light"],
    reviews: [{ author: "I. Kowalski", rating: 4, title: "Whisper quiet, means it", body: "Can't hear it at all from the next room, exactly as advertised." }],
  },
  {
    id: "hk-005",
    category: "home",
    title: "Amberglow Scented Candle Trio",
    brand: "Fern & Field",
    price: 34.0,
    listPrice: 34.0,
    rating: 4.6,
    reviewCount: 2214,
    stock: 110,
    image: img("amberglow-candles"),
    gallery: [img("amberglow-candles"), img("amberglow-2")],
    description: "Set of three soy-wax candles: Cedar & Amber, Fig Leaf, and Sea Salt Linen. 45-hour burn time each.",
    bullets: ["100% soy wax", "45-hour burn time per candle", "Cotton wicks, no lead", "Reusable ceramic vessels"],
    reviews: [{ author: "O. Nilsen", rating: 5, title: "Fig Leaf is incredible", body: "Bought two more sets as gifts after trying Fig Leaf." }],
  },
  {
    id: "hk-006",
    category: "home",
    title: "Riverbend Bamboo Cutting Board Set",
    brand: "Fern & Field",
    price: 28.5,
    listPrice: 35.0,
    rating: 4.5,
    reviewCount: 1876,
    stock: 97,
    image: img("bamboo-boards"),
    gallery: [img("bamboo-boards"), img("bamboo-2")],
    description: "Set of 3 organic bamboo cutting boards with juice grooves and built-in handles.",
    bullets: ["Set of 3 sizes", "Juice groove on large board", "Naturally antimicrobial bamboo"],
    reviews: [{ author: "P. Costa", rating: 4, title: "Sturdy and lightweight", body: "No warping after a month of daily use, just don't soak them." }],
  },
  {
    id: "hk-007",
    category: "home",
    title: "Northloom Cotton Throw Blanket",
    brand: "Fern & Field",
    price: 36.0,
    listPrice: 44.0,
    rating: 4.7,
    reviewCount: 940,
    stock: 71,
    image: img("northloom-throw"),
    gallery: [img("northloom-throw"), img("northloom-2")],
    description: "Chunky-knit 100% cotton throw blanket, 50×60 inches, machine washable.",
    bullets: ["100% cotton, chunky knit", "50 × 60 inches", "Machine washable, cold cycle"],
    variants: { color: ["Oat", "Moss", "Charcoal", "Dusty Rose"] },
    reviews: [{ author: "R. Haas", rating: 5, title: "Softer than photos suggest", body: "Heavier and cozier than I expected for the price." }],
  },

  // -------------------------------------------------------------- FASHION
  {
    id: "fs-001",
    category: "fashion",
    title: "Ridgeline Straight-Leg Jeans",
    brand: "Wharf & Co.",
    price: 44.0,
    listPrice: 58.0,
    rating: 4.2,
    reviewCount: 3312,
    stock: 150,
    badge: "Under $50",
    image: img("ridgeline-jeans"),
    gallery: [img("ridgeline-jeans"), img("ridgeline-2")],
    description: "Mid-rise straight-leg jeans in rigid organic cotton denim, garment-washed for a broken-in feel.",
    bullets: ["98% organic cotton, 2% elastane", "Mid-rise, straight leg", "Garment-washed finish"],
    variants: { size: ["28", "30", "32", "34", "36"], color: ["Indigo", "Washed Black", "Stone"] },
    reviews: [{ author: "T. Kowalczyk", rating: 4, title: "True to size", body: "Ordered my usual size, fit exactly as expected out of the dryer." }],
  },
  {
    id: "fs-002",
    category: "fashion",
    title: "Cascade Merino Crewneck Sweater",
    brand: "Wharf & Co.",
    price: 68.0,
    listPrice: 85.0,
    rating: 4.6,
    reviewCount: 1420,
    stock: 48,
    image: img("cascade-sweater"),
    gallery: [img("cascade-sweater"), img("cascade-2")],
    description: "100% merino wool crewneck, fine-gauge knit, naturally moisture-wicking and odor-resistant.",
    bullets: ["100% merino wool", "Fine 12-gauge knit", "Machine washable on wool cycle"],
    variants: { size: ["XS", "S", "M", "L", "XL"], color: ["Charcoal", "Cream", "Forest"] },
    reviews: [{ author: "L. Bergstrom", rating: 5, title: "Worth the price", body: "Doesn't pill after multiple wears like cheaper merino blends I've owned." }],
  },
  {
    id: "fs-003",
    category: "fashion",
    title: "Overland Canvas Field Jacket",
    brand: "Wharf & Co.",
    price: 92.0,
    listPrice: 120.0,
    rating: 4.5,
    reviewCount: 780,
    stock: 26,
    image: img("overland-jacket"),
    gallery: [img("overland-jacket"), img("overland-2"), img("overland-3")],
    description: "Waxed canvas field jacket with corduroy collar, four utility pockets, and a quilted lining.",
    bullets: ["12oz waxed canvas shell", "Quilted flannel lining", "Corduroy collar", "4 exterior pockets"],
    variants: { size: ["S", "M", "L", "XL"], color: ["Olive", "Rust"] },
    reviews: [{ author: "M. Fontaine", rating: 5, title: "Built like it'll last decades", body: "Heavy-duty stitching throughout, this is not fast fashion." }],
  },
  {
    id: "fs-004",
    category: "fashion",
    title: "Lowtide Canvas Sneakers",
    brand: "Wharf & Co.",
    price: 39.0,
    listPrice: 49.0,
    rating: 4.1,
    reviewCount: 2530,
    stock: 200,
    image: img("lowtide-sneakers"),
    gallery: [img("lowtide-sneakers"), img("lowtide-2")],
    description: "Low-top canvas sneakers with a recycled-rubber sole and cushioned insole.",
    bullets: ["Canvas upper", "Recycled rubber outsole", "Removable cushioned insole"],
    variants: { size: ["7", "8", "9", "10", "11", "12"], color: ["White", "Navy", "Black"] },
    reviews: [{ author: "A. Ricci", rating: 4, title: "Comfortable out of the box", body: "No break-in period needed, wore them all day one on day one." }],
  },
  {
    id: "fs-005",
    category: "fashion",
    title: "Amble Leather Crossbody Bag",
    brand: "Fernweh Goods",
    price: 76.0,
    listPrice: 95.0,
    rating: 4.7,
    reviewCount: 610,
    stock: 33,
    image: img("amble-bag"),
    gallery: [img("amble-bag"), img("amble-2")],
    description: "Full-grain leather crossbody bag with adjustable strap and antique brass hardware.",
    bullets: ["Full-grain leather", "Adjustable crossbody strap", "Interior zip and slip pockets"],
    variants: { color: ["Cognac", "Espresso"] },
    reviews: [{ author: "N. Devereux", rating: 5, title: "Ages beautifully", body: "Already developing a nice patina after a month of daily use." }],
  },

  // ---------------------------------------------------------- OFFICE/SCHOOL
  {
    id: "of-001",
    category: "office",
    title: "Meridian A5 Dot-Grid Notebook (3-Pack)",
    brand: "Ledger House",
    price: 24.0,
    listPrice: 30.0,
    rating: 4.8,
    reviewCount: 4021,
    stock: 140,
    badge: "Bestseller",
    image: img("meridian-notebooks"),
    gallery: [img("meridian-notebooks"), img("meridian-2")],
    description: "Set of 3 dot-grid notebooks, 160 pages each, 120gsm paper, lay-flat binding.",
    bullets: ["3 notebooks, 160 pages each", "120gsm dot-grid paper", "Lay-flat binding", "Elastic closure + pen loop"],
    variants: { color: ["Black", "Terracotta", "Sage"] },
    reviews: [{ author: "C. Dupont", rating: 5, title: "No ghosting with fountain pens", body: "Paper handles wet fountain pen ink far better than expected at this price." }],
  },
  {
    id: "of-002",
    category: "office",
    title: "Cambridge Adjustable Standing Desk Converter",
    brand: "Norrbyte",
    price: 129.0,
    listPrice: 159.0,
    rating: 4.4,
    reviewCount: 1955,
    stock: 38,
    image: img("standing-desk"),
    gallery: [img("standing-desk"), img("standing-desk-2")],
    description: "Gas-spring standing desk converter, dual-tier, fits up to a 32-inch monitor.",
    bullets: ["Gas-spring height adjustment", "Dual-tier keyboard tray", "Supports up to 33 lbs"],
    reviews: [{ author: "W. Larsen", rating: 4, title: "Smooth height adjustment", body: "One-handed lift is genuinely effortless even at max load." }],
  },
  {
    id: "of-003",
    category: "office",
    title: "Fieldstone Calculator, Solar + Battery",
    brand: "Ledger House",
    price: 12.99,
    listPrice: 15.99,
    rating: 4.5,
    reviewCount: 3110,
    stock: 250,
    image: img("fieldstone-calc"),
    gallery: [img("fieldstone-calc")],
    description: "12-digit desktop calculator with dual solar and battery power, large tilt display.",
    bullets: ["12-digit large display", "Solar + battery hybrid power", "Tax and currency conversion keys"],
    reviews: [{ author: "H. Yamada", rating: 5, title: "Exactly what I needed", body: "Simple, reliable, buttons have satisfying tactile feedback." }],
  },
  {
    id: "of-004",
    category: "office",
    title: "Backpack Study Set: Bag + Pencil Case",
    brand: "Wharf & Co.",
    price: 54.0,
    listPrice: 68.0,
    rating: 4.6,
    reviewCount: 2789,
    stock: 90,
    badge: "Back to school",
    image: img("study-backpack"),
    gallery: [img("study-backpack"), img("study-backpack-2")],
    description: "Water-resistant 22L backpack with padded 15-inch laptop sleeve, plus matching zip pencil case.",
    bullets: ["22L capacity, padded laptop sleeve fits 15\"", "Water-resistant recycled fabric", "Includes matching pencil case"],
    variants: { color: ["Charcoal", "Sky Blue", "Blush"] },
    reviews: [{ author: "E. Solis", rating: 5, title: "Held up all semester", body: "Zippers still feel new after a full school year of daily use." }],
  },

  // ------------------------------------------------------------ OUTDOORS
  {
    id: "od-001",
    category: "outdoors",
    title: "Basecamp 2-Person Backpacking Tent",
    brand: "Fernweh Goods",
    price: 149.0,
    listPrice: 189.0,
    rating: 4.6,
    reviewCount: 1340,
    stock: 29,
    image: img("basecamp-tent"),
    gallery: [img("basecamp-tent"), img("basecamp-2"), img("basecamp-3")],
    description: "Freestanding 2-person backpacking tent, 3-season, 3.2kg trail weight, full-coverage rainfly.",
    bullets: ["2-person, 3-season", "3.2kg trail weight", "Full-coverage rainfly", "2 vestibules for gear storage"],
    reviews: [{ author: "J. Marsh", rating: 5, title: "Survived a windy ridge camp", body: "Held up in 30mph gusts on an exposed ridgeline without issue." }],
  },
  {
    id: "od-002",
    category: "outdoors",
    title: "Emberlight Camp Stove, Dual Burner",
    brand: "Fernweh Goods",
    price: 68.0,
    listPrice: 85.0,
    rating: 4.4,
    reviewCount: 964,
    stock: 41,
    image: img("emberlight-stove"),
    gallery: [img("emberlight-stove"), img("emberlight-2")],
    description: "Compact dual-burner propane camp stove with wind guards and push-button ignition.",
    bullets: ["Dual burner, 20,000 BTU combined", "Push-button piezo ignition", "Folding wind guards"],
    reviews: [{ author: "K. Bennett", rating: 4, title: "Boils fast even in wind", body: "Wind guards make a real difference at exposed sites." }],
  },
  {
    id: "od-003",
    category: "outdoors",
    title: "Tideline Insulated Water Bottle 32oz",
    brand: "Fernweh Goods",
    price: 27.0,
    listPrice: 34.0,
    rating: 4.7,
    reviewCount: 6210,
    stock: 180,
    badge: "Deal",
    image: img("tideline-bottle"),
    gallery: [img("tideline-bottle"), img("tideline-2")],
    description: "Double-wall vacuum insulated stainless steel bottle, keeps drinks cold 24h / hot 12h.",
    bullets: ["32oz capacity", "24h cold / 12h hot retention", "Leak-proof flip lid", "18/8 stainless steel"],
    variants: { color: ["Moss", "Slate", "Sunrise"] },
    reviews: [{ author: "F. Okonkwo", rating: 5, title: "Ice still there after 20 hours", body: "Left ice cubes in overnight camping, still solid the next afternoon." }],
  },
  {
    id: "od-004",
    category: "outdoors",
    title: "Switchback Trekking Poles (Pair)",
    brand: "Fernweh Goods",
    price: 42.0,
    listPrice: 52.0,
    rating: 4.5,
    reviewCount: 815,
    stock: 66,
    image: img("switchback-poles"),
    gallery: [img("switchback-poles")],
    description: "Collapsible aluminum trekking poles with cork grips and quick-lock adjustment.",
    bullets: ["Adjustable 24\"–54\"", "Cork grip, sweat-resistant", "Quick-lock flip adjustment", "Includes carry bag"],
    reviews: [{ author: "S. Ahonen", rating: 4, title: "Locks hold under real weight", body: "No slipping even on steep, loaded descents." }],
  },

  // -------------------------------------------------------------- TOYS
  {
    id: "ty-001",
    category: "toys",
    title: "Orbitcraft Building Block Set, 500pc",
    brand: "Bramblewood Toys",
    price: 34.99,
    listPrice: 44.99,
    rating: 4.8,
    reviewCount: 3987,
    stock: 105,
    badge: "Bestseller",
    image: img("orbitcraft-blocks"),
    gallery: [img("orbitcraft-blocks"), img("orbitcraft-2")],
    description: "500-piece building block set with 6 build guides, compatible with major block brands.",
    bullets: ["500 pieces, 6 build guides", "Compatible with major block brands", "Storage tub included"],
    reviews: [{ author: "D. Fischer", rating: 5, title: "Kids play with it constantly", body: "My 7-year-old has rebuilt every guide model and started freestyling." }],
  },
  {
    id: "ty-002",
    category: "toys",
    title: "Riftwood Cooperative Board Game",
    brand: "Bramblewood Toys",
    price: 29.0,
    listPrice: 35.0,
    rating: 4.6,
    reviewCount: 1240,
    stock: 58,
    image: img("riftwood-game"),
    gallery: [img("riftwood-game"), img("riftwood-2")],
    description: "Cooperative strategy board game for 2–5 players, ages 10+, 45–60 minute playtime.",
    bullets: ["2–5 players, cooperative", "Ages 10+", "45–60 minute playtime"],
    reviews: [{ author: "Q. Ibarra", rating: 5, title: "Great family game night pick", body: "Difficulty scales well, works for mixed adult/kid groups." }],
  },
  {
    id: "ty-003",
    category: "toys",
    title: "Pemberton Plush Fox, 14in",
    brand: "Bramblewood Toys",
    price: 18.0,
    listPrice: 22.0,
    rating: 4.9,
    reviewCount: 2870,
    stock: 210,
    image: img("pemberton-fox"),
    gallery: [img("pemberton-fox")],
    description: "Ultra-soft plush fox, 14 inches, machine washable, weighted for cozy hugging.",
    bullets: ["14 inches tall", "Machine washable cover", "Weighted base"],
    reviews: [{ author: "M. Delgado", rating: 5, title: "Softest plush we own", body: "Survived the washing machine multiple times with zero fraying." }],
  },
  {
    id: "ty-004",
    category: "toys",
    title: "Skyline Kite, Ripstop Nylon",
    brand: "Fernweh Goods",
    price: 16.5,
    listPrice: 20.0,
    rating: 4.3,
    reviewCount: 540,
    stock: 130,
    image: img("skyline-kite"),
    gallery: [img("skyline-kite")],
    description: "Single-line delta kite in ripstop nylon, easy assembly, includes 100ft line and carry bag.",
    bullets: ["Ripstop nylon canopy", "Fiberglass frame", "Includes 100ft line and reel"],
    reviews: [{ author: "B. Larsson", rating: 4, title: "Flies in light wind", body: "Got it airborne in what felt like barely-there breeze." }],
  },

  // ------------------------------------------------------------- BEAUTY
  {
    id: "bt-001",
    category: "beauty",
    title: "Quietwater Oat Milk Body Lotion",
    brand: "Fern & Field",
    price: 16.0,
    listPrice: 20.0,
    rating: 4.5,
    reviewCount: 2980,
    stock: 160,
    image: img("quietwater-lotion"),
    gallery: [img("quietwater-lotion"), img("quietwater-2")],
    description: "Fragrance-light oat milk body lotion for sensitive skin, fast-absorbing, non-greasy.",
    bullets: ["Colloidal oat extract", "Fragrance-light formula", "Fast-absorbing, non-greasy"],
    reviews: [{ author: "P. Andresen", rating: 5, title: "Finally, no irritation", body: "Only lotion that hasn't triggered my eczema in years." }],
  },
  {
    id: "bt-002",
    category: "beauty",
    title: "Driftgrain Exfoliating Body Scrub",
    brand: "Fern & Field",
    price: 14.0,
    listPrice: 18.0,
    rating: 4.4,
    reviewCount: 1660,
    stock: 140,
    image: img("driftgrain-scrub"),
    gallery: [img("driftgrain-scrub")],
    description: "Brown sugar and coconut oil body scrub, gently exfoliating, leaves skin soft without residue.",
    bullets: ["Brown sugar + coconut oil base", "No microplastics", "16oz jar"],
    reviews: [{ author: "G. Osei", rating: 4, title: "Smells incredible", body: "Coconut scent is strong but not overpowering, lingers pleasantly." }],
  },
  {
    id: "bt-003",
    category: "beauty",
    title: "Northbloom Vitamin C Serum",
    brand: "Fern & Field",
    price: 22.0,
    listPrice: 28.0,
    rating: 4.2,
    reviewCount: 3450,
    stock: 95,
    badge: "Deal",
    image: img("northbloom-serum"),
    gallery: [img("northbloom-serum"), img("northbloom-2")],
    description: "15% vitamin C brightening serum with vitamin E and ferulic acid, 1oz dropper bottle.",
    bullets: ["15% L-ascorbic acid", "With vitamin E and ferulic acid", "Fragrance-free, 1oz bottle"],
    reviews: [{ author: "A. Costa", rating: 4, title: "Noticed brightening in 3 weeks", body: "A little tingle on first use but no irritation after that." }],
  },
  {
    id: "bt-004",
    category: "beauty",
    title: "Softline Bamboo Safety Razor",
    brand: "Fern & Field",
    price: 24.0,
    listPrice: 24.0,
    rating: 4.6,
    reviewCount: 780,
    stock: 70,
    image: img("softline-razor"),
    gallery: [img("softline-razor")],
    description: "Bamboo-handle safety razor with 5 stainless steel blades, plastic-free packaging.",
    bullets: ["Bamboo handle", "Includes 5 replacement blades", "Plastic-free packaging"],
    reviews: [{ author: "R. Sundberg", rating: 5, title: "Closer shave than cartridges", body: "Took two tries to get the angle right, then noticeably better shave." }],
  },
];

// ---------------------------------------------------------------------------
// Demo accounts for the login flow. Passwords are plain text on purpose —
// this is a client-only mock auth, not a real credential store.
// ---------------------------------------------------------------------------
export const DEMO_USERS = [
  {
    id: "u-1",
    email: "reader@fable.test",
    password: "fable123",
    firstName: "Amara",
    lastName: "Islam",
    addresses: [
      {
        label: "Home",
        line1: "42 Willowmere Lane",
        city: "Khulna",
        region: "Khulna Division",
        postalCode: "9100",
        country: "Bangladesh",
      },
    ],
  },
  {
    id: "u-2",
    email: "demo@fable.test",
    password: "demo1234",
    firstName: "Demo",
    lastName: "Account",
    addresses: [
      {
        label: "Home",
        line1: "12 Bramblewood Court",
        city: "Dhaka",
        region: "Dhaka Division",
        postalCode: "1207",
        country: "Bangladesh",
      },
    ],
  },
];

// Flat rate + free-shipping threshold used by the cart/checkout calculations.
export const SHIPPING = {
  flatRate: 4.99,
  freeThreshold: 35,
};

// Simple destination-based tax rates used by checkout — not real tax logic,
// just enough variance to make the summary feel alive.
export const TAX_RATE = 0.075;